export function ListWords(){

const myList = [
  { word: "anchor", riddle: "I keep a ship from drifting though I never leave the sea bed. What am I?" },
  { word: "compass", riddle: "I always point the way even when I don’t move. What am I?" },
  { word: "lantern", riddle: "I carry light in your hand when night falls. What am I?" },
  { word: "quill", riddle: "Once feathered, I helped write history. What am I?" },
  { word: "harbor", riddle: "Ships find safety in my arms when storms arrive. What am I?" },
  { word: "echo", riddle: "You say something and I say it back — but I have no voice. What am I?" },
  { word: "anvil", riddle: "A blacksmith pounds on me so others may take shape. What am I?" },
  { word: "goblet", riddle: "I hold toast and wine high at a feast. What am I?" },
  { word: "tapestry", riddle: "Threads arrange to tell a picture without a brush. What am I?" },
  { word: "harp", riddle: "Strings sing when fingers pass and make soft music. What am I?" },
  { word: "scroll", riddle: "Words roll up in me like a secret waiting to be unfurled. What am I?" },
  { word: "oasis", riddle: "A patch of life appears where heat and sand surround. What am I?" },
  { word: "ember", riddle: "I glow low after the flames have calmed. What am I?" },
  { word: "forge", riddle: "Heat, hammer and metal meet at my hearth. What am I?" },
  { word: "brook", riddle: "I babble and wind through fields on my way. What am I?" },
  { word: "spire", riddle: "I rise to a point and crown a building. What am I?" },
  { word: "veil", riddle: "I hide what’s beneath with a thin, soft layer. What am I?" },
  { word: "cloak", riddle: "I wrap you in shadow and keep secrets close. What am I?" },
  { word: "helm", riddle: "At my wheel a captain turns fate’s direction. What am I?" },
  { word: "voyage", riddle: "A journey begins with me and ends when you arrive. What am I?" },
  { word: "reef", riddle: "I am a hidden danger and a sea’s garden at once. What am I?" },
  { word: "mast", riddle: "High above the deck I hold the sails like wings. What am I?" },
  { word: "fable", riddle: "Animals speak in me to teach a simple truth. What am I?" },
  { word: "myth", riddle: "I explain the unexplainable with tales of gods and heroes. What am I?" },
  { word: "rune", riddle: "A carved mark that once held secret meanings. What am I?" },
  { word: "potion", riddle: "A small draught can change a fate — real or imagined. What am I?" },
  { word: "relic", riddle: "I survived ages and now carry someone else’s history. What am I?" },
  { word: "monarch", riddle: "One rules a realm by title, not by vote. What am I?" },
  { word: "scepter", riddle: "A ruler holds me to show authority though I do nothing. What am I?" },
  { word: "citadel", riddle: "A fortress on the hill guards the city below. What am I?" },
  { word: "moat", riddle: "A watery ring protects walls from unwelcome boots. What am I?" },
  { word: "crown", riddle: "I rest on a head and mark sovereignty. What am I?" },
  { word: "trident", riddle: "Three prongs make me a fish-king’s symbol. What am I?" },
  { word: "throne", riddle: "I hold the one who rules, though I rule not myself. What am I?" },
  { word: "parchment", riddle: "Animal skin turned to pages holds old laws and poems. What am I?" },
  { word: "quartz", riddle: "Clear and hard, I ring when struck and keep time in devices. What am I?" },
  { word: "amber", riddle: "In me insects can be trapped in golden stone. What am I?" },
  { word: "ivory", riddle: "A tusk once part of an elephant, now shaped and polished. What am I?" },
  { word: "silhouette", riddle: "A dark outline tells a shape when light falls behind. What am I?" },
  { word: "labyrinth", riddle: "Twists and turns meant to confuse those who enter. What am I?" },
  { word: "beacon", riddle: "I warn or guide from a height with steady light. What am I?" },
  { word: "marble", riddle: "Stone turned smooth and used for statues and games. What am I?" },
  { word: "vessel", riddle: "I carry cargo or crew across water or in the body. What am I?" },
  { word: "dagger", riddle: "Short and sharp, I serve close work where reach is small. What am I?" },
  { word: "flute", riddle: "Breathe across my hole and a tune will follow. What am I?" },
  { word: "lyre", riddle: "A small harp that once accompanied poets’ words. What am I?" },
  { word: "pendant", riddle: "I hang near the heart and can hold a memory. What am I?" },
  { word: "amulet", riddle: "Worn against bad luck though the magic is faith. What am I?" },
  { word: "mirror", riddle: "I show you yourself though I have no sight. What am I?" },
  { word: "dragon", riddle: "A legendary beast that breathes fire in many tales. What am I?" },
  { word: "griffin", riddle: "Part eagle, part lion — a guardian of treasure in myth. What am I?" },
  { word: "phoenix", riddle: "I die in flame and rise again from my own ashes. What am I?" },
  { word: "chimera", riddle: "A being made of parts from different animals in old stories. What am I?" },
  { word: "serpent", riddle: "I slither and hiss and sometimes symbolize cunning. What am I?" },
  { word: "falcon", riddle: "A swift raptor that hunters used to fly on a fist. What am I?" },
  { word: "owl", riddle: "I watch the night and am a symbol of wisdom. What am I?" },
  { word: "panther", riddle: "A large cat that moves like a shadow through the undergrowth. What am I?" },
  { word: "lynx", riddle: "A forest cat with tufted ears and sharp sight. What am I?" },
  { word: "stag", riddle: "A noble deer wearing branched antlers as a crown. What am I?" },
  { word: "antler", riddle: "A branching crown that sheds and regrows each year. What am I?" },
  { word: "blossom", riddle: "A flower’s moment of opening in spring’s first warmth. What am I?" },
  { word: "vine", riddle: "I climb and cling and often bear fruit along the way. What am I?" },
  { word: "thistle", riddle: "Prickly and proud, I protect with sharp points. What am I?" },
  { word: "fern", riddle: "Fronds unfold like green lace from the forest floor. What am I?" },
  { word: "willow", riddle: "My long branches droop and whisper by the water. What am I?" },
  { word: "cedar", riddle: "A scented wood that resists worms and time. What am I?" },
  { word: "ash", riddle: "I remain after fire and I name a hardwood tree. What am I?" },
  { word: "maple", riddle: "I give sweet sap and wear blazing color in autumn. What am I?" },
  { word: "spruce", riddle: "Evergreen and conical, often chosen for winter lights. What am I?" },
  { word: "acorn", riddle: "A small nut that can become a mighty oak someday. What am I?" },
  { word: "pinecone", riddle: "Scales hold seeds safe until they are ready to fly. What am I?" },
  { word: "pebble", riddle: "Small stone smoothed by rivers and footsteps. What am I?" },
  { word: "boulder", riddle: "A massive rock that refuses to be moved by hand. What am I?" },
  { word: "crag", riddle: "A sharp rock face jutting from a mountain’s skin. What am I?" },
  { word: "canyon", riddle: "A deep wound carved by patient rivers over time. What am I?" },
  { word: "dune", riddle: "I shift with wind and stand like a sand wave. What am I?" },
  { word: "ocean", riddle: "An endless blue that holds more life than land. What am I?" },
  { word: "tide", riddle: "I come and go with the moon’s quiet pull. What am I?" },
  { word: "current", riddle: "I move beneath the surface and carry ships along. What am I?" },
  { word: "wave", riddle: "I travel across the sea and break on the shore. What am I?" },
  { word: "isle", riddle: "A small patch of land surrounded by water. What am I?" },
  { word: "cave", riddle: "Dark mouth in a cliff where echoes sleep. What am I?" },
  { word: "glacier", riddle: "A river of ice that moves slower than memory. What am I?" },
  { word: "aurora", riddle: "Colors dance at the poles when solar winds visit. What am I?" },
  { word: "horizon", riddle: "Where sky and earth seem to meet, always just out of reach. What am I?" },
  { word: "summit", riddle: "The highest point where climbers plant their flags. What am I?" },
  { word: "valley", riddle: "Low between hills, a place where rivers may sleep. What am I?" },
  { word: "grove", riddle: "A small stand of trees that feels like a neighborhood. What am I?" },
  { word: "orchard", riddle: "Rows of fruit trees meant to feed many mouths. What am I?" },
  { word: "pasture", riddle: "A green field where animals graze in peace. What am I?" },
  { word: "field", riddle: "Open land grown for food or games. What am I?" },
  { word: "marsh", riddle: "Wet ground where reeds and frogs politely argue. What am I?" },
  { word: "lagoon", riddle: "A small sheltered pool near the sea or a coral reef. What am I?" },
  { word: "hearth", riddle: "The home’s warm heart where meals and stories begin. What am I?" },
  { word: "saddle", riddle: "I sit on a horse so a rider may stay balanced. What am I?" },
  { word: "keystone", riddle: "The center stone that keeps an arch from falling. What am I?" },
  { word: "keel", riddle: "I run along a ship’s bottom and keep it steady in waves. What am I?" },
  { word: "rudder", riddle: "I steer a vessel when the helmsman commands. What am I?" },
  { word: "prow", riddle: "The forward point that splits the sea for a ship. What am I?" },
  { word: "masthead", riddle: "At the top of the mast you find me, often a flag or light. What am I?" },
  { word: "telescope", riddle: "I bring distant stars and moons close to your eye. What am I?" },
  { word: "portrait", riddle: "I freeze a face in color or shadow on a wall. What am I?" },
  { word: "ledger", riddle: "I keep accounts and truths written in rows. What am I?" },
  { word: "vault", riddle: "I lock away treasures with heavy doors and codes. What am I?" },
  { word: "lanes", riddle: "Rows for travel inside towns: people follow my lines. What am I?" },
  { word: "orchid", riddle: "Delicate and exotic, I bloom for careful hands. What am I?" },
  { word: "satchel", riddle: "I carry books and lunches across your shoulder. What am I?" },
  { word: "garrison", riddle: "A group of soldiers stands ready inside my walls. What am I?" },
  { word: "cobalt", riddle: "A blue mineral used for pigments and metal alloys. What am I?" },
  { word: "mariner", riddle: "A sailor who reads the weather and the waves. What am I?" },
  { word: "compote", riddle: "Fruit cooked with sugar served in a dish sweet and warm. What am I?" },
  { word: "tinder", riddle: "Small dry stuff that welcomes the first spark. What am I?" },
  { word: "glacier", riddle: "Slow and vast, I carve valleys as I creep. What am I?" },
  { word: "hammock", riddle: "I cradle sleepers between two trees with a sway. What am I?" },
  { word: "spinner", riddle: "I whirl to show motion or to make yarn. What am I?" },
  { word: "canopy", riddle: "I hang above heads, sheltering from sun or storm. What am I?" },
  { word: "kiln", riddle: "I bake clay into pottery with fierce, even heat. What am I?" },
  { word: "glisten", riddle: "I sparkle faintly after a fresh rain. What am I?" },
  { word: "barley", riddle: "A grain that feeds and ferments into a golden drink. What am I?" },
  { word: "cobble", riddle: "Rounded stones laid in streets for old-time paths. What am I?" },
  { word: "tavern", riddle: "A noisy place where strangers share stories and ale. What am I?" },
  { word: "paddle", riddle: "I push water back so a small boat moves forward. What am I?" },
  { word: "laneway", riddle: "A narrow passage between buildings where secrets hide. What am I?" },
  { word: "quarry", riddle: "Stone is cut from me to build walls and halls. What am I?" },
  { word: "harvest", riddle: "I gather the crop when fields are full and golden. What am I?" },
  { word: "spiral", riddle: "I wind inward or outward with graceful turns. What am I?" },
  { word: "sonnet", riddle: "Fourteen lines that fall in rhyme to praise or mourn. What am I?" },
  { word: "tablet", riddle: "A flat slab for notes, carved words, or modern touch. What am I?" },
  { word: "cobweb", riddle: "Silken traps in corners where tiny hunters live. What am I?" },
  { word: "lanolin", riddle: "A waxy cream from fleece that soothes dry skin. What am I?" },
  { word: "galleon", riddle: "A large wooden ship once used for trade and gold. What am I?" },
  { word: "mastiff", riddle: "A giant dog, calm and watchful at the gate. What am I?" },
  { word: "orchard", riddle: "Rows of fruit trees that promise harvest and pies. What am I?" },
  { word: "fletcher", riddle: "One who makes arrows with care and feather. What am I?" },
  { word: "sundial", riddle: "I tell time by the sun’s shadow on my face. What am I?" },
  { word: "stockade", riddle: "Wooden posts stand tight to keep foes outside. What am I?" },
  { word: "galleon", riddle: "Tall masts and broad decks once carried colonies and spice. What am I?" },
  { word: "tremor", riddle: "A small shaking that hints at something larger below. What am I?" },
  { word: "mantle", riddle: "A cloak for earth’s interior or a fireplace shelf. What am I?" },
  { word: "cairn", riddle: "Stacked stones mark a path where maps are scarce. What am I?" },
  { word: "keystone", riddle: "The final wedge that keeps an arch from falling. What am I?" },
  { word: "pylon", riddle: "I stand tall to mark limits or support wires. What am I?" },
  { word: "horizon", riddle: "Where sky and land seem to meet but never touch. What am I?" },
  { word: "jetty", riddle: "A narrow structure reaching into water for mooring. What am I?" },
  { word: "mosaic", riddle: "Tiny colored pieces form a bigger picture underfoot. What am I?" },
  { word: "lantern", riddle: "A portable light that glows when oil or bulb warms. What am I?" },
  { word: "corset", riddle: "I shape the body within fabric and laces. What am I?" },
  { word: "manuscript", riddle: "Handwritten pages holding stories before printing. What am I?" },
  { word: "ledger", riddle: "Columns of numbers that show who owes what. What am I?" },
  { word: "chimney", riddle: "I rise above the roof to carry smoke to the sky. What am I?" },
  { word: "butter", riddle: "Cream churned smooth into a golden spread. What am I?" },
  { word: "bramble", riddle: "Tangled stems with thorns protect ripe fruit inside. What am I?" },
  { word: "crescent", riddle: "A slim curved moon or shape like a thin banana. What am I?" },
  { word: "dovecote", riddle: "A home for pigeons tucked high on a wall. What am I?" },
  { word: "emboss", riddle: "Raised patterns pressed into leather or paper for texture. What am I?" },
  { word: "furlong", riddle: "A measure once used for tracks — short but old. What am I?" },
  { word: "gimlet", riddle: "A small tool that drills with a twisting bite. What am I?" },
  { word: "holler", riddle: "A loud call that crosses fields and valleys. What am I?" },
  { word: "inkwell", riddle: "A small cup that holds the black fluid for pens. What am I?" },
  { word: "jettison", riddle: "To toss cargo overboard to save the ship. What am I?" },
  { word: "keelhaul", riddle: "A brutal old punishment dragged along the hull — historic and harsh. What am I?" },
  { word: "lute", riddle: "A pear-shaped instrument plucked to accompany songs. What am I?" },
  { word: "mire", riddle: "Sticky mud that traps feet and slows the brave. What am I?" },
  { word: "notary", riddle: "An official who certifies signatures and truths. What am I?" },
  { word: "obelisk", riddle: "A tall tapering stone monument pointing upward. What am I?" },
  { word: "pastiche", riddle: "A creative pasting together of styles to imitate. What am I?" },
  { word: "quarry", riddle: "The hunted or the place stone is carved and cut. What am I?" },
  { word: "rivet", riddle: "A metal pin that holds sheets together with pressure. What am I?" },
  { word: "shanty", riddle: "A short, simple song sailors sing while they work. What am I?" },
  { word: "tiller", riddle: "I move the rudder when a helmsman pulls my arm. What am I?" },
  { word: "urchin", riddle: "A street child or a spiky sea creature — both small and quick. What am I?" },
  { word: "vagrant", riddle: "One who wanders with few possessions and many miles. What am I?" },
  { word: "wattle", riddle: "Interwoven sticks plastered for walls or chicken shelter. What am I?" },
  { word: "yaw", riddle: "To twist a ship or plane off its straight path — a slight turn. What am I?" },
  { word: "zephyr", riddle: "A gentle west wind that barely stirs the leaves. What am I?" },
  { word: "anther", riddle: "The pollen-bearing tip of a flower’s stamen. What am I?" },
  { word: "belfry", riddle: "A tower that houses a bell for town calls. What am I?" },
  { word: "claret", riddle: "A wine deep in red, often from Bordeaux — rich and dry. What am I?" },
  { word: "docket", riddle: "A short list of items slated for attention or court. What am I?" },
  { word: "eider", riddle: "A soft down from a sea duck used for warm quilts. What am I?" },
  { word: "farrow", riddle: "A group of piglets born at once to a sow. What am I?" },
  { word: "gambit", riddle: "An opening sacrifice made to gain later advantage. What am I?" },
  { word: "hutch", riddle: "A small wooden house for rabbits or storage. What am I?" },
  { word: "irons", riddle: "Metal tools or prison shackle — depends on the context. What am I?" },
  { word: "joist", riddle: "A beam that supports floors and keeps houses steady. What am I?" },
  { word: "kiosk", riddle: "A small stand that sells newspapers or snacks on a corner. What am I?" },
  { word: "lorry", riddle: "A heavy vehicle that hauls cargo on roads. What am I?" },
  { word: "manor", riddle: "A large country house with lands and history. What am I?" },
  { word: "nimbus", riddle: "A rain cloud or a halo of light around something holy. What am I?" },
  { word: "oust", riddle: "To remove someone from power or place abruptly. What am I?" },
  { word: "polo", riddle: "A sport where riders strike a ball with long mallets. What am I?" },
  { word: "quill", riddle: "A feather used long ago to sign letters and laws. What am I?" },
  { word: "harpoon", riddle: "A long spear for catching sea creatures from a boat. What am I?" },
  { word: "compass", riddle: "I point north so you won’t lose your way. What am I?" },
  { word: "ledger", riddle: "Pages of records that keep track of money and trades. What am I?" },
  { word: "lantern", riddle: "Carry me and darkness becomes passable. What am I?" },
  { word: "keystone", riddle: "I lock an arch in place and keep it standing. What am I?" },
  { word: "anvil", riddle: "Hammer meets me when a smith shapes metal. What am I?" },
  { word: "trowel", riddle: "A small spade for spreading mortar or planting seeds. What am I?" },
  { word: "harrow", riddle: "I break and smooth the earth after the plow. What am I?" },
  { word: "sundial", riddle: "The sun’s shadow on me tells you the hour. What am I?" },
  { word: "quarry", riddle: "Stone is cut from my face to build the city. What am I?" },
  { word: "bracket", riddle: "I support shelves or hold pieces in place. What am I?" },
  { word: "casket", riddle: "I hold a final rest or a precious keepsake. What am I?" },
  { word: "oyster", riddle: "I hide a pearl in my shell beneath the sea. What am I?" },
  { word: "tiller", riddle: "I move the rudder to steer a small boat. What am I?" },
  { word: "hollow", riddle: "An empty space inside a hill or tree trunk. What am I?" },
  { word: "masonry", riddle: "Stone and mortar work that builds walls and towers. What am I?" },
  { word: "pylon", riddle: "Tall and upright, I mark limits or hold power lines. What am I?" },
  { word: "anchor", riddle: "I bite the seabed so ships may sleep. What am I?" },
  { word: "cobble", riddle: "Rounded stones laid to make a historic street. What am I?" },
  { word: "gimlet", riddle: "A small tool that drills with a twisting bite. What am I?" },
  { word: "obelisk", riddle: "A tall, tapering stone that points to the sky. What am I?" },
  { word: "shingle", riddle: "I cover roofs in overlapping rows to keep out rain. What am I?" },
  { word: "wicket", riddle: "Small gate or cricket target — both marked and small. What am I?" },
  { word: "parlay", riddle: "To bet winnings again or convert one thing into another in talk. What am I?" },
  { word: "galleon", riddle: "A large wooden ship of old, laden with sails and stores. What am I?" },
  { word: "buoy", riddle: "I float and mark danger or safe spots for ships. What am I?" },
  { word: "cairn", riddle: "Stacked stones that guide travelers across barren ground. What am I?" },
  { word: "chalice", riddle: "A special cup used in rituals or royal feasts. What am I?" },
  { word: "dynamo", riddle: "I turn motion into electricity for lamps and tools. What am I?" },
  { word: "easel", riddle: "I hold a canvas upright while an artist paints. What am I?" },
  { word: "funnel", riddle: "Pour through me and spills become polite. What am I?" },
  { word: "gimbal", riddle: "I keep an object level even when my frame tilts. What am I?" },
  { word: "hoodoo", riddle: "A strange rock pillar shaped by wind and rain. What am I?" },
  { word: "ingot", riddle: "Metal cast into a bar for storage or later crafting. What am I?" },
  { word: "jackal", riddle: "A cunning canine that scavenges at dusk. What am I?" },
  { word: "kiln", riddle: "Clay goes in soft — pottery comes out hard after my heat. What am I?" },
  { word: "lathe", riddle: "I spin wood or metal while tools shape its form. What am I?" },
  { word: "mausoleum", riddle: "A grand tomb built to remember someone forever. What am I?" },
  { word: "niche", riddle: "A small recessed space in a wall for a statue or shelf. What am I?" },
  { word: "oarlock", riddle: "I hold an oar in place and let it pivot for rowing. What am I?" },
  { word: "pulley", riddle: "I change direction and ease the lifting of heavy loads. What am I?" },
  { word: "quern", riddle: "Stone hand-mill used by old kitchens to grind grain. What am I?" },
  { word: "rafter", riddle: "Beams that support a roof and bear the snow. What am I?" },
  { word: "scythe", riddle: "A curved blade swung to reap fields of grain. What am I?" },
  { word: "thresher", riddle: "I separate grain from stalk with rhythmic motion. What am I?" },
  { word: "urn", riddle: "A vessel that can hold ashes or flowers on display. What am I?" },
  { word: "vane", riddle: "I spin to show which way the wind is blowing. What am I?" },
  { word: "wharf", riddle: "Boats tie up beside me to unload or greet the shore. What am I?" },
  { word: "yoke", riddle: "I bind two animals together to pull a plow. What am I?" },
  { word: "zinc", riddle: "A bluish metal that rusts less and coats to protect. What am I?" },
  { word: "abutment", riddle: "Support at an arch’s ends that keeps it from falling. What am I?" },
  { word: "bevel", riddle: "An angled edge cut to fit two pieces together smoothly. What am I?" },
  { word: "carpentry", riddle: "The craft of shaping wood into useful things and homes. What am I?" },
  { word: "dovetail", riddle: "Interlocking joints that hold drawers without nails. What am I?" },
  { word: "escutcheon", riddle: "A decorative plate around a keyhole or handle. What am I?" },
  { word: "fluting", riddle: "Vertical grooves carved in columns for elegant texture. What am I?" },
  { word: "grommet", riddle: "A ring that reinforces holes for ropes or wires. What am I?" },
  { word: "hatchway", riddle: "An opening into the deck or below of a vessel or building. What am I?" },
  { word: "inkstand", riddle: "A small desk companion that holds ink for dipping pens. What am I?" },
  { word: "jetty", riddle: "I stretch into water to protect a harbor or dock. What am I?" },
  { word: "keel", riddle: "I run the ship’s length underneath to keep her upright. What am I?" },
  { word: "larder", riddle: "A cool room where food is stored before the feast. What am I?" },
  { word: "midship", riddle: "At the center of a ship between bow and stern. What am I?" },
  { word: "navel", riddle: "A belly’s mark and a central point on an orange. What am I?" },
  { word: "outboard", riddle: "An engine mounted on a boat’s exterior for thrust. What am I?" },
  { word: "plumbline", riddle: "A weighted string used to test what’s straight and true. What am I?" },
  { word: "quoin", riddle: "Cornerstones that strengthen a building’s edge. What am I?" },
  { word: "ramrod", riddle: "A rod used to pack a musket — old soldier’s tool. What am I?" },
  { word: "sconce", riddle: "A wall-mounted holder for candlelight or lamp. What am I?" },
  { word: "tramline", riddle: "Tracks that guide a tram through the city’s vein. What am I?" },
  { word: "underlay", riddle: "A layer beneath that cushions and evens a floor. What am I?" },
  { word: "vernier", riddle: "A precise scale used to read measurements small. What am I?" },
  { word: "wheelhouse", riddle: "Where the captain stands to pilot the vessel. What am I?" },
  { word: "yawline", riddle: "A rope used to control a ship’s angle or sway. What am I?" },
  { word: "zealot", riddle: "One driven by fervor, often blind to softer words. What am I?" },
  { word: "abut", riddle: "To touch or lean against another thing closely. What am I?" },
  { word: "binnacle", riddle: "I hold a ship’s compass and keep it safe at the helm. What am I?" },
  { word: "capstan", riddle: "A rotating drum sailors wind ropes around to haul heavy loads. What am I?" },
  { word: "davit", riddle: "A small crane used to lower boats to the sea. What am I?" },
  { word: "escapement", riddle: "A mechanism that lets gears advance step by step in clocks. What am I?" },
  { word: "fender", riddle: "I cushion boats when they kiss the dock. What am I?" },
  { word: "gaff", riddle: "A spar that helps hold a sail’s upper edge. What am I?" },
  { word: "hawser", riddle: "A thick rope used for towing or mooring heavy ships. What am I?" },
  { word: "idler", riddle: "A wheel that turns freely to guide a belt or chain. What am I?" },
  { word: "jibboom", riddle: "A spar extending the bowsprit to hold extra sails. What am I?" },
  { word: "kedge", riddle: "A small anchor used for maneuvering a ship short distances. What am I?" },
  { word: "logbook", riddle: "A captain’s diary noting course, weather and time. What am I?" },

 ];
  const randomIndex = Math.floor(Math.random() * myList.length);
    return myList[randomIndex];
}